#!/usr/bin/env node
// Validate the test-method mapping and print coverage per group and triage level (phase 2, D-025). No dependencies.
//
// Usage (from the repository root, Node 24):
//   node scripts/wcag/test-methods.mjs            validate and print summary tables (Markdown)
//   node scripts/wcag/test-methods.mjs --group=keyboard   list the criteria of one group (primary and secondary)
//   node scripts/wcag/test-methods.mjs --write-recipes    fill the criteria table in testing-kit/recipes/<group>.md
//
// Reads data/wcag/success-criteria.json and data/mappings/sc-test-methods.json. Exits 1 on any validation error.

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const read = (p) => JSON.parse(readFileSync(join(root, p), 'utf8'));

const scs = read('data/wcag/success-criteria.json').successCriteria;
const { groups, criteria } = read('data/mappings/sc-test-methods.json');

const ENUMS = {
  automation: ['full', 'partial', 'none'],
  ai: ['likely', 'possible', 'unlikely'],
  human: ['must', 'should', 'optional'],
};
const NEEDS = ['dom', 'accessibility-tree', 'screenshot', 'focus-trace', 'zoomed-render', 'text-spacing-render',
  'interaction', 'media', 'timing', 'multi-page'];

const errors = [];
const groupIds = Object.keys(groups);
for (const sc of scs) {
  const c = criteria[sc.id];
  if (!c) { errors.push(`${sc.id}: missing`); continue; }
  if (c.level !== sc.level) errors.push(`${sc.id}: level ${c.level} != ${sc.level}`);
  if (!groupIds.includes(c.groups?.primary)) errors.push(`${sc.id}: unknown primary group ${c.groups?.primary}`);
  for (const g of c.groups?.secondary ?? []) if (!groupIds.includes(g)) errors.push(`${sc.id}: unknown secondary group ${g}`);
  if (c.groups?.primary === 'automated' && c.automation?.level !== 'full') errors.push(`${sc.id}: primary automated needs automation full`);
  for (const [k, values] of Object.entries(ENUMS)) {
    if (!values.includes(c[k]?.level)) errors.push(`${sc.id}: ${k}.level ${c[k]?.level}`);
  }
  for (const n of c.ai?.needs ?? []) if (!NEEDS.includes(n)) errors.push(`${sc.id}: unknown ai need ${n}`);
  if (!c.rationale) errors.push(`${sc.id}: no rationale`);
}
for (const id of Object.keys(criteria)) if (!scs.some((sc) => sc.id === id)) errors.push(`${id}: not a WCAG 2.x criterion`);

if (errors.length) {
  console.error(`${errors.length} validation errors:\n${errors.join('\n')}`);
  process.exit(1);
}

const entries = scs.map((sc) => [sc.id, criteria[sc.id]]);
// Markdown table of the criteria in one group: primary first, then secondary, in WCAG order.
function groupTable(group) {
  const url = Object.fromEntries(scs.map((sc) => [sc.id, sc.url]));
  const rows = [];
  for (const role of ['primary', 'secondary']) {
    for (const [id, c] of entries) {
      const inRole = role === 'primary' ? c.groups.primary === group : c.groups.secondary?.includes(group);
      if (inRole) rows.push(`| [${id} ${c.handle}](${url[id]}) | ${c.level} | ${role} | ${c.automation.level} | ${c.ai.level} | ${c.human.level} |`);
    }
  }
  return `| Criterion | Level | Role | Automation | AI | Human |\n|---|---|---|---|---|---|\n${rows.join('\n')}`;
}

const groupArg = process.argv.find((a) => a.startsWith('--group='))?.slice(8);
if (groupArg) {
  if (!groupIds.includes(groupArg)) { console.error(`Unknown group ${groupArg}`); process.exit(1); }
  console.log(groupTable(groupArg));
  process.exit(0);
}

if (process.argv.includes('--write-recipes')) {
  const marker = /<!-- criteria:start -->[\s\S]*?<!-- criteria:end -->/;
  for (const g of groupIds) {
    const file = join(root, 'testing-kit/recipes', `${g}.md`);
    if (!existsSync(file)) { console.error(`No recipe for ${g}`); process.exitCode = 1; continue; }
    const text = readFileSync(file, 'utf8');
    if (!marker.test(text)) { console.error(`No criteria markers in ${g}.md`); process.exitCode = 1; continue; }
    const block = `<!-- criteria:start -->\n<!-- Generated by scripts/wcag/test-methods.mjs --write-recipes from data/mappings/sc-test-methods.json. Do not edit. -->\n${groupTable(g)}\n<!-- criteria:end -->`;
    writeFileSync(file, text.replace(marker, block));
    console.log(`Wrote criteria table in testing-kit/recipes/${g}.md`);
  }
  process.exit();
}

const count = (pred) => entries.filter(([, c]) => pred(c)).length;
console.log(`${entries.length} criteria valid, ${count((c) => c.review === 'pending')} pending review\n`);
console.log(`| Group | Primary | Secondary |\n|---|---|---|`);
for (const g of groupIds) {
  console.log(`| ${groups[g].name} | ${count((c) => c.groups.primary === g)} | ${count((c) => c.groups.secondary?.includes(g))} |`);
}
for (const [k, values] of Object.entries(ENUMS)) {
  console.log(`\n| ${k} | ${values.join(' | ')} |\n|---|${values.map(() => '---|').join('')}`);
  console.log(`| criteria | ${values.map((v) => count((c) => c[k].level === v)).join(' | ')} |`);
}
